# Generated by Django 6.0.6 on 2026-06-25 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('course', models.CharField(choices=[('ENGLISH', 'English'), ('MATHEMATICS', 'Mathematics'), ('SCIENCE', 'Science')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SessionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('duration', models.DurationField()),
                ('hourly_rate', models.DecimalField(decimal_places=6, max_digits=10)),
                ('status', models.CharField(choices=[('COMPLETED', 'Completed'), ('ON_GOING', 'On_going'), ('CANCELLED', 'Cancelled'), ('PAUSED', 'Paused'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=55)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.student')),
            ],
        ),
    ]
