# Generated by Django 6.0.6 on 2026-06-27 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionlog',
            name='status',
            field=models.CharField(choices=[('COMPLETED', 'Completed'), ('ON_GOING', 'On_going'), ('CANCELLED', 'Cancelled'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=55),
        ),
        migrations.AlterField(
            model_name='sessionlog',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='tracker.student'),
        ),
    ]
